Update package.json
faye updated to 1.2.0 on the weekend. Since then I'm getting an error when running buster :

Error: Cannot find module 'faye/browser/faye-browser-min'

So could you please use the old version in the package.json